nome = input ("Escreva seu nome: ")
v1 = int(input("Escreva o primeiro número: "))
v2 = int(input("Escreva o segundo número: "))
soma = (v1+v2)
sub = (v1-v2)
div = (v1/v2)
mult = (v1*v2)
resto = (v1%v2)

print(f"Olá, {nome} Aqui estão os resultados das operações matemáticas dos dois números informados")
print(f"O resultado da soma é: {soma}")
print(f"O resultado da subtração é: {sub}")
print(f"O resultado da divisão é: {div}")
print(f"O resultado da multiplicação é: {mult}")
print(f"O resultado do resto da divisão é: {resto}")

